name: itrue-haproxy
adopt-info: haproxy
summary: Fast and reliable load balancing reverse proxy
description: |
  Fast and reliable load balancing reverse proxy
issues: https://github.com/IsaacJT/haproxy-snap/issues
source-code: https://github.com/IsaacJT/haproxy-snap
website: https://www.haproxy.org/
license: GPL-3.0-only
title: HAProxy

base: core26
grade: stable
confinement: strict

apps:
  haproxy:
    command: usr/sbin/haproxy -Ws -f $SNAP_DATA/haproxy.cfg
    start-timeout: 30s
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

hooks:
  install:
    command-chain:
      - snap/command-chain/install.sh

parts:
  haproxy:
    plugin: nil
    stage-packages:
      - haproxy
    override-build: |
      craftctl default
      craftctl set version=$(dpkg-deb -f \
        "${CRAFT_PART_BUILD}/../stage_packages/haproxy_"*.deb Version)
    override-prime: |
      craftctl default
      rm -f etc/haproxy/haproxy.cfg
      rm -rf lib
      rm -rf usr/share
      rm -rf var
  local:
    after: [haproxy]
    plugin: dump
    source-type: local
    source: snap/local
